### PR TITLE
[Feat] Bump walk-sync; Add support for walk-sync opts

### LINKED ISSUE #18: [Feat | Docs] Add typings for tree-sync
New feature proposal | Documentation

**What?**
Let's add a TypeScript type definition file for the tree-sync module! It'll be included with the package's files and referenced using the `types` property in `package.json`.

**Why?**
- TypeScript users don't have to define the module in their own repos, and they can get other IDE niceties out of the box (if their IDE knows how to reason about TypeScript).
- Provides public documentation of tree-sync's API.

_(FYI: I'm already working on this at present - posting an issue ahead of a PR for visibility and feedback. Barring any objections I'll have an PR posted for review soon... ish. Thanks for considering!)_

### LINKED ISSUE #19: [Feat | Chore] Bump walk-sync; Add pass-through of options to walk-sync
New feature request | Maintenance Chore

**What?**
Bump walk-sync to pick up latest features. Then, provide the ability to pass options through to walk-sync, so we can opt to selectively include or omit files and folders from tree syncing.

**Why?**
- Some use cases might call for omitting or selectively picking directories to sync. Notably, this can help solve an issue where running tree-sync on a folder with a symlink to a parent directory can result in an infinite loop (that eventually crashes when the filename gets too long) by opting to omit the symlinked dir (if the use case allows for it). (https://github.com/joliss/node-walk-sync/issues/30)
- Brings dependency up to date.

_(FYI: I'm already working on this at present - posting an issue ahead of a PR for visibility and feedback. Barring any objections I'll have an PR posted for review soon... ish. Thanks for considering!)_

### PR DESCRIPTION
**Pull request by zimmi88**
- Bumps walk-sync to 0.3.3.
- The latest version of walk-sync has options for selectively including or excluding files and directories. Add a parameter to tree-sync through which these options can be passed in and passed along to walk-sync. Only whitelisted options `globs` and `ignore` are passed through.
- Bump version of tree-sync to 1.3.0.

Resolves #19.

Notes:
- I was a little torn on whether to include `globs`, since it can be easy to run into some pitfalls with missing dirs using that option. In the end, I leaned towards including it for completeness and adding a warning of what to watch out for. If we'd rather stick to excluding only, let me know and I'll update.

Thanks in advance for the review!

(updated to reflect typings being spun off into their own PR)

### CODE REVIEW

**Comment by rwjblue** [comment]
> Add a typings file for tree-sync and include in package.json.

Would you mind separating this change into a separate PR? It seems unrelated to the majority of the work here, and I don't want to hold things up just for that...

**Comment by zimmi88** [comment]
Thanks for the feedback. I'll update the PR to spin off the typings into a new PR and update the readme.

**Comment by stefanpenner** [comment]
i like it!

**Comment by stefanpenner** [comment]
released as v1.3.0 🎉

**Pull request merged**
